/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./src/components/layout/AppBreadcrumb.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Divider: typeof import('primevue/divider')['default']
    DynamicDialog: typeof import('primevue/dynamicdialog')['default']
    FullscreenToggle: typeof import('./src/components/layout/FullscreenToggle.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Image: typeof import('primevue/image')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LanguageSelector: typeof import('./src/components/layout/LanguageSelector.vue')['default']
    LoaderSpinner: typeof import('./src/components/LoaderSpinner.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Mask: typeof import('./src/components/Mask.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    MenuItem: typeof import('./src/components/layout/MenuItem.vue')['default']
    Message: typeof import('primevue/message')['default']
    NotificationMenu: typeof import('./src/components/layout/NotificationMenu.vue')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    PromptDialog: typeof import('./src/components/PromptDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    SidebarMenu: typeof import('./src/components/layout/SidebarMenu.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TagsView: typeof import('./src/components/layout/TagsView.vue')['default']
    ThemeSwitcher: typeof import('./src/components/layout/ThemeSwitcher.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    UserMenu: typeof import('./src/components/layout/UserMenu.vue')['default']
  }
}
